/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dfad58ee65a325e6cbd8a1900fc6ff1c)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	RUNWAY_TRUSTED_PROXY_HOSTS: "pinch-runway.asherthenoble.chatgpt.site";
	BASIQ_API_BASE_URL: "https://au-api.basiq.io";
	BASIQ_API_VERSION: "3.0";
	RUNWAY_AUTOMATION_MODE: "off";
	RUNWAY_ENABLE_LIVE_DELIVERY: "0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RUNWAY_TRUSTED_PROXY_HOSTS" | "BASIQ_API_BASE_URL" | "BASIQ_API_VERSION" | "RUNWAY_AUTOMATION_MODE" | "RUNWAY_ENABLE_LIVE_DELIVERY">> {}
}
