/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 21727f5b79885a082ee3929b2993c421)
interface __BaseEnv_Env {
	DB: D1Database;
	BASIQ_API_BASE_URL: "https://au-api.basiq.io";
	BASIQ_API_VERSION: "3.0";
	RUNWAY_AUTOMATION_MODE: "off";
	RUNWAY_ENABLE_LIVE_DELIVERY: "0";
	RUNWAY_DATA_SOURCE: string;
	PINCH_APPLICATION_ID: string;
	PINCH_SECRET_KEY: string;
	PINCH_API_VERSION: string;
	PINCH_API_BASE_URL: string;
	PINCH_PUBLISHABLE_KEY: string;
	RUNWAY_ENABLE_SANDBOX_SETUP_UI: string;
	RUNWAY_SANDBOX_SETUP_TOKEN: string;
	BASIQ_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BASIQ_API_BASE_URL" | "BASIQ_API_VERSION" | "RUNWAY_AUTOMATION_MODE" | "RUNWAY_ENABLE_LIVE_DELIVERY" | "RUNWAY_DATA_SOURCE" | "PINCH_APPLICATION_ID" | "PINCH_SECRET_KEY" | "PINCH_API_VERSION" | "PINCH_API_BASE_URL" | "PINCH_PUBLISHABLE_KEY" | "RUNWAY_ENABLE_SANDBOX_SETUP_UI" | "RUNWAY_SANDBOX_SETUP_TOKEN" | "BASIQ_API_KEY">> {}
}
