"use client";
import { useState } from "react";
export function PaymentLinkAction({ invoiceId }: { invoiceId: string }) {
  const [link, setLink] = useState<string>(); const [state, setState] = useState<"idle" | "working" | "ready" | "error">("idle"); const [message, setMessage] = useState("");
  async function create() { setState("working"); setMessage(""); try { const r = await fetch("/api/collection-actions/payment-link", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ invoice_id: invoiceId }) }); const p = await r.json() as { payment_link?: { url?: string }; error?: string }; if (!r.ok || !p.payment_link?.url) throw new Error(p.error ?? "Payment link was not created."); setLink(p.payment_link.url); setState("ready"); } catch (e) { setState("error"); setMessage(e instanceof Error ? e.message : "Payment link was not created."); } }
  async function email() { setState("working"); const r = await fetch(`/api/collection-actions/${encodeURIComponent(invoiceId)}/email`, { method: "POST" }); const p = await r.json().catch(() => ({})) as { error?: string }; if (!r.ok) { setState("error"); setMessage(p.error ?? "Could not email the payer."); return; } setState("ready"); setMessage("Payment link emailed and recorded. We chased them for you."); }
  if (state === "ready" && link) return <div className="ping-actions"><strong>Payment link ready to email</strong><button type="button" onClick={email}>Email payer</button><a href={link} target="_blank" rel="noreferrer">Open payment link</a><button type="button" onClick={() => navigator.clipboard.writeText(link)}>Copy link</button>{message && <span>{message}</span>}</div>;
  return <div className="ping-actions"><button type="button" onClick={create} disabled={state === "working"}>{state === "working" ? "Creating payment link…" : "Create payment link"}</button>{state === "error" && <span role="alert">{message}</span>}</div>;
}
