/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --cwd workers/ai-gateway --env-interface AiGatewayEnv --include-runtime=false --strict-vars=false` (hash: 7160d1d3f7b6f345fd9135008dafaed2)
interface __BaseEnv_AiGatewayEnv {
	AI: Ai;
	WORKERS_AI_GATEWAY_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_AiGatewayEnv {}
}
interface AiGatewayEnv extends __BaseEnv_AiGatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKERS_AI_GATEWAY_TOKEN">> {}
}
